!HISTORY 5

HDLERR	F	cannot create database handle: %1$s
NTS failed to create a new Berkeley DB database handle. Check for
previous errors logged by the Berkeley DB subsystem and correct the
problem.  (This message may also be caused by a programming error.)
.

RLNFAIL	F	cannot set record length: %1$s
NTS failed to configure an internal Berkeley DB option.  Check for
previous errors logged by the Berkeley DB subsystem and correct the
problem.  (This message may also be caused by a programming error.)
.

PADFAIL	F	cannot set record padding character: %1$s
NTS failed to configure an internal Berkeley DB option.  Check for
previous errors logged by the Berkeley DB subsystem and correct the
problem.  (This message may also be caused by a programming error.)
.

EXTNFAIL	F	cannot set database extent size: %1$s
NTS failed to configure an internal Berkeley DB option.  Check for
previous errors logged by the Berkeley DB subsystem and correct the
problem.  (This message may also be caused by a programming error.)
.

OPNFAIL	F	cannot open database "%1$s": %2$s
NTS failed to open a Berkeley DB database. Check for previous errors 
logged by the Berkeley DB subsystem and correct the problem.
.

ASSCFAIL	F	cannot associate message-id database: %1$s
NTS failed to configure an internal Berkeley DB option.  Check for
previous errors logged by the Berkeley DB subsystem and correct the
problem.  (This message may also be caused by a programming error.)
.

EXPIRED	I	expired %lu entries from the history database
NTS successfully ran regular history expired.
.

