!LOG

OPNFAIL	F	cannot open log file "%s": %s
NTS failed to open the configured log file.  Ensure that the correct 
path is specified and that the NTS user has write access to the file.
.

INCFAIL	F	cannot open incoming log file "%s": %s
NTS failed to open the configured incoming log file.  Ensure that the
correct path is specified and that the NTS user has write access to the
file.
.

PATHFAIL	F	cannot open path log file "%s": %s
NTS failed to open the configured path log file.  Ensure that the 
correct path is specified and that the NTS user has write access to the 
file.
.

