language: c
compiler:
  - gcc
  - clang
env:
  - CPPFLAGS="-Wall -Wno-unused-parameter -Wno-parentheses -Wno-implicit-int -Wno-missing-field-initializers"
script: sudo apt-get -y install libdb5.1-dev &&  mkdir build && cd build && ../configure --prefix=$HOME/nts-install && make && make install
